# site settings
title: Mountainscapes
subtitle: Irrigation and Landscaping
email: matt@mountainscapes.co
description: Servicing Whistler Squamish and Permberton
baseurl: "/" # the subpath of your site, e.g. /blog
url: mountainscapes.co
author: Matt Francisty
street_address:
city:
state:
zip_code:
country:
phone: (604) 698-7555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
